Import types with the type-only import
Fix the TS error after upgrading to the version 5.

Error: 'ParametersToOmitOnCreate' is a type and must be imported using
a type-only import when 'verbatimModuleSyntax' is enabled.
Error: 'IAddress' is a type and must be imported using a type-only
import when 'verbatimModuleSyntax' is enabled.